version: "3"
services:
  # основное приложение, запускается на отладочном сервере
  webapp:
    build: .
    depends_on:
      - db
    volumes:
      - .:/code
      - ~/.cache/pypoetry:/root/.cache/pypoetry # проброс кэша poetry, чтобы не грузить каждый раз при сборке
      - staticfiles_volume:/code/staticfiles/  # Общий том для статики
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-bimd1yez5_9#nau+@nh$$hw%ugaw+oc5^g_"
      - "DJANGO_DEBUG=True"
      - "CSRF_TRUSTED_HOSTS=127.0.0.1,localhost"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/1"
      # - "DJANGO_SECURE_SSL_REDIRECT="
      # - "DJANGO_SECURE_HSTS_SECONDS="
      # - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS="
      # - "DJANGO_SECURE_HSTS_PRELOAD="
      # - "DJANGO_SESSION_COOKIE_SECURE="
      # - "DJANGO_CSRF_COOKIE_SECURE="
      # # данные для почтового сервера для подтверждения регистрации
      # - "DJANGO_EMAIL_HOST_PASSWORD="
      # - "DJANGO_EMAIL_HOST_USER="
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    restart: unless-stopped

  db:
    build: './deploy/build/db'
    volumes:
      - db_eve:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    restart: unless-stopped

  nginx:
    build: './deploy/build/nginx'
    depends_on:
      - webapp
    volumes:
      - staticfiles_volume:/usr/share/nginx/html/static:ro  # Монтируем статику в Nginx
      - ./deploy/log/nginx:/var/log/nginx #log файлы.
      - ./deploy/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro #Конфигурация nginx.
      - ./deploy/conf/nginx/conf.d:/etc/nginx/conf.d:ro #Конфигурация nginx, более ручная
      - ./deploy/conf/nginx/ssl:/etc/nginx/ssl:ro #сертификаты
    ports:
      - 80:80
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  celery:
    build: .
    depends_on:
      - redis
      - webapp
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-code-a$$+st+m@s!xy9g6h_!%)%v_=1q)5d"
      - "CSRF_TRUSTED_HOSTS=127.0.0.1,localhost"
      - "DJANGO_DEBUG=False"
    command: celery -A config.celery_app.app worker --loglevel=info -E
    volumes:
      - .:/code
      - ~/.cache/pypoetry:/root/.cache/pypoetry
    restart: unless-stopped

  flower:
    image: mher/flower
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    restart: unless-stopped

volumes:
  staticfiles_volume:
  redis_data:
  db_eve:
    external: true
