version: "3"
services:
  webapp:
    # python + poetry + gunicorn + psycopg2-binary + environs[django] + django + сайт
    build: .
    depends_on:
      - db
    volumes:
      - .:/code
    # env_file: .env
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-t#lsan$$1-a@ci)o2bimd1yez5_9#nau+@nh$$hw%ugaw+oc5^g_"
      - "DJANGO_DEBUG=True"
      - "CSRF_TRUSTED_HOSTS=127.0.0.1,localhost"
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    # command: gunicorn config.wsgi -b 0.0.0.0:8000
  db:
    build: './deploy/build/db'
    volumes:
      - db_eve:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
  nginx:
    build: './deploy/build/nginx'
    depends_on:
      - webapp
    volumes:
      - ./deploy/log/nginx:/var/log/nginx #log файлы.
      - ./deploy/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro #Конфигурация nginx.
      - ./deploy/conf/nginx/conf.d:/etc/nginx/conf.d:ro #Конфигурация nginx
      - ./deploy/conf/nginx/ssl:/etc/nginx/ssl:ro #сертификаты
    ports:
      - 80:80
volumes:
  db_eve:
    external: true
