version: '3.8'
services:
  web:
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    # command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-t#lsan$$1-a@ci)o2bimd1yez5_9#nau+@nh$$hw%ugaw+oc5^g_"
      - "DJANGO_DEBUG=True"
      - "DJANGO_EMAIL_HOST_PASSWORD=fadu lcex ynym qksg"
      - "DJANGO_EMAIL_HOST_USER=eliskrommer390@gmail.com"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
  db:
    image: postgres:16
    volumes:
      - db_eve:/var/lib/postgresql/data/
    environment:
      # - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
volumes:
  db_eve:
    external: true


