# Generated by Django 5.0.2 on 2024-02-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellations',
            fields=[
                ('name', models.CharField(null=True)),
                ('constellation_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('name', models.CharField(null=True)),
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('constellation_id', models.IntegerField(null=True)),
                ('name', models.CharField(null=True)),
                ('planets', models.JSONField(null=True)),
                ('position', models.JSONField(null=True)),
                ('security_class', models.CharField(null=True)),
                ('security_status', models.FloatField(null=True)),
                ('star_id', models.IntegerField(null=True)),
                ('stargates', models.JSONField(null=True)),
                ('stations', models.JSONField(null=True)),
                ('system_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
