# Generated by Django 5.0.2 on 2024-03-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constellations',
        ),
        migrations.DeleteModel(
            name='Systems',
        ),
        migrations.AddField(
            model_name='regions',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
