# Generated by Django 5.0.2 on 2024-03-07 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0002_delete_constellations_delete_systems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constellations',
            fields=[
                ('constellation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(null=True)),
                ('position_x', models.IntegerField(null=True)),
                ('position_y', models.IntegerField(null=True)),
                ('position_z', models.IntegerField(null=True)),
                ('region_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbeve_universe.regions')),
            ],
        ),
    ]
