# Generated by Django 5.0.2 on 2024-03-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0003_constellations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constellations',
            old_name='region_id',
            new_name='region',
        ),
    ]
