# Generated by Django 5.0.2 on 2024-03-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0004_rename_region_id_constellations_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constellations',
            name='position_x',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='constellations',
            name='position_y',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='constellations',
            name='position_z',
            field=models.BigIntegerField(null=True),
        ),
    ]
