# Generated by Django 5.0.2 on 2024-03-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0005_alter_constellations_position_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constellations',
            name='position_x',
            field=models.DecimalField(decimal_places=0, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='constellations',
            name='position_y',
            field=models.DecimalField(decimal_places=0, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='constellations',
            name='position_z',
            field=models.DecimalField(decimal_places=0, max_digits=32, null=True),
        ),
    ]
