# Generated by Django 5.0.2 on 2024-03-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0006_alter_constellations_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellations',
            name='response_body',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='regions',
            name='response_body',
            field=models.JSONField(null=True),
        ),
    ]
