# Generated by Django 5.0.2 on 2024-03-08 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0007_constellations_response_body_regions_response_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('name', models.CharField(null=True)),
                ('position_x', models.DecimalField(decimal_places=0, max_digits=32, null=True)),
                ('position_y', models.DecimalField(decimal_places=0, max_digits=32, null=True)),
                ('position_z', models.DecimalField(decimal_places=0, max_digits=32, null=True)),
                ('security_class', models.CharField(null=True)),
                ('security_status', models.FloatField(null=True)),
                ('system_id', models.IntegerField(primary_key=True, serialize=False)),
                ('response_body', models.JSONField(null=True)),
                ('constellation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbeve_universe.constellations')),
            ],
        ),
    ]
