# Generated by Django 5.0.2 on 2024-03-08 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0008_systems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('age', models.IntegerField(null=True)),
                ('luminosity', models.FloatField(null=True)),
                ('name', models.CharField(null=True)),
                ('radius', models.IntegerField(null=True)),
                ('spectral_class', models.CharField(null=True)),
                ('star_id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField(null=True)),
                ('solar_system', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbeve_universe.systems')),
            ],
        ),
    ]
