# Generated by Django 5.0.2 on 2024-03-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0010_stars_response_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='age',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='radius',
            field=models.BigIntegerField(null=True),
        ),
    ]
