# Generated by Django 5.0.2 on 2024-03-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0011_alter_stars_age_alter_stars_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodlines',
            fields=[
                ('bloodline_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Factions',
            fields=[
                ('faction_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('race_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('station_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
