# Generated by Django 5.0.2 on 2024-04-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0012_bloodlines_factions_races_stations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celestials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_change', models.DateTimeField(auto_now=True, null=True)),
                ('response_body', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
