# Generated by Django 5.0.2 on 2024-04-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0013_celestials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Celestials',
        ),
        migrations.AddField(
            model_name='stars',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
