# Generated by Django 5.0.2 on 2024-04-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_universe', '0014_delete_celestials_stars_dt_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellations',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='regions',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='systems',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
