# Generated by Django 5.0.2 on 2024-03-11 04:03

import dbeve_social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlliancesIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # указание icons_path вызывало ошибку в последующих миграциях - так как там эта функция уже удалена
                # ('px128x128', models.ImageField(null=True, upload_to=dbeve_social.models.icons_path)),
                # ('px64x64', models.ImageField(null=True, upload_to=dbeve_social.models.icons_path)),
                ('px128x128', models.ImageField(null=True)),
                ('px64x64', models.ImageField(null=True)),
            ],
        ),
    ]
