# Generated by Django 5.0.2 on 2024-03-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliancesicons',
            name='px128x128',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='alliancesicons',
            name='px64x64',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
