# Generated by Django 5.0.2 on 2024-03-13 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0002_alter_alliancesicons_px128x128_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlliancesIcons',
        ),
    ]
