# Generated by Django 5.0.2 on 2024-03-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbeve_social', '0003_delete_alliancesicons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliances',
            fields=[
                ('alliance_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_founded', models.DateTimeField(null=True)),
                ('name', models.CharField(null=True)),
                ('ticker', models.CharField(null=True)),
                ('response_body', models.JSONField(null=True)),
            ],
        ),
    ]
