# Generated by Django 5.0.2 on 2024-03-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliances',
            name='nameicon',
            field=models.CharField(null=True),
        ),
    ]
