# Generated by Django 5.0.2 on 2024-03-14 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0005_alliances_nameicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporations',
            fields=[
                ('corporation_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('alliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_corporation', to='dbeve_social.alliances')),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('character_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('alliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.alliances')),
                ('corporation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.corporations')),
            ],
        ),
        migrations.AddField(
            model_name='alliances',
            name='creator_corporation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_corporation', to='dbeve_social.corporations'),
        ),
        migrations.AddField(
            model_name='alliances',
            name='executor_corporation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_corporation', to='dbeve_social.corporations'),
        ),
    ]
