# Generated by Django 5.0.2 on 2024-03-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0006_corporations_characters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alliances',
            name='creator_corporation',
        ),
        migrations.RemoveField(
            model_name='alliances',
            name='executor_corporation',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='alliance',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='corporation',
        ),
        migrations.RemoveField(
            model_name='corporations',
            name='alliance',
        ),
        migrations.AddField(
            model_name='characters',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='gender',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='response_body',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='security_status',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corporations',
            name='date_founded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='corporations',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corporations',
            name='member_count',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='corporations',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='corporations',
            name='response_body',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='corporations',
            name='shares',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='corporations',
            name='tax_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='corporations',
            name='ticker',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='corporations',
            name='url',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='corporations',
            name='war_eligible',
            field=models.BooleanField(null=True),
        ),
    ]
