# Generated by Django 5.0.2 on 2024-03-16 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0007_remove_alliances_creator_corporation_and_more'),
        ('dbeve_universe', '0012_bloodlines_factions_races_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliances',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_alliance', to='dbeve_social.characters'),
        ),
        migrations.AddField(
            model_name='alliances',
            name='creator_corporation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_corporation', to='dbeve_social.corporations'),
        ),
        migrations.AddField(
            model_name='alliances',
            name='executor_corporation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_corporation', to='dbeve_social.corporations'),
        ),
        migrations.AddField(
            model_name='characters',
            name='alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.alliances'),
        ),
        migrations.AddField(
            model_name='characters',
            name='bloodline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_universe.bloodlines'),
        ),
        migrations.AddField(
            model_name='characters',
            name='corporation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.corporations'),
        ),
        migrations.AddField(
            model_name='characters',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_universe.factions'),
        ),
        migrations.AddField(
            model_name='characters',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_universe.races'),
        ),
        migrations.AddField(
            model_name='corporations',
            name='alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.alliances'),
        ),
        migrations.AddField(
            model_name='corporations',
            name='ceo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo', to='dbeve_social.characters'),
        ),
        migrations.AddField(
            model_name='corporations',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_corporation', to='dbeve_social.characters'),
        ),
        migrations.AddField(
            model_name='corporations',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_universe.factions'),
        ),
        migrations.AddField(
            model_name='corporations',
            name='home_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_universe.stations'),
        ),
    ]
