# Generated by Django 5.0.2 on 2024-03-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0008_alliances_creator_alliances_creator_corporation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliances',
            name='list_associated_corp',
            field=models.JSONField(null=True),
        ),
    ]
