# Generated by Django 5.0.2 on 2024-03-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0009_alliances_list_associated_corp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alliances',
            name='list_associated_corp',
        ),
    ]
