# Generated by Django 5.0.2 on 2024-03-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0010_remove_alliances_list_associated_corp'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='nameicon',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='corporations',
            name='nameicon',
            field=models.CharField(null=True),
        ),
    ]
