# Generated by Django 5.0.2 on 2024-03-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0011_characters_nameicon_corporations_nameicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliances',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_alliance', to='dbeve_social.characters'),
        ),
        migrations.AlterField(
            model_name='alliances',
            name='creator_corporation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_corporation', to='dbeve_social.corporations'),
        ),
    ]
