# Generated by Django 5.0.2 on 2024-04-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0012_alter_alliances_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
    ]
