# Generated by Django 5.0.2 on 2024-04-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0013_characters_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliances',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='corporations',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
