# Generated by Django 5.0.2 on 2024-04-22 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_items', '0001_initial'),
        ('dbeve_social', '0014_alliances_dt_change_characters_dt_change_and_more'),
        ('dbeve_universe', '0016_bloodlines_dt_change_bloodlines_response_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Killmails',
            fields=[
                ('dt_change', models.DateTimeField(auto_now=True, null=True)),
                ('response_body', models.JSONField(null=True)),
                ('killmail_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('killmail_time', models.DateTimeField()),
                ('position_x', models.DecimalField(decimal_places=0, max_digits=32)),
                ('position_y', models.DecimalField(decimal_places=0, max_digits=32)),
                ('position_z', models.DecimalField(decimal_places=0, max_digits=32)),
                ('ship_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_items.shiptypes')),
                ('solar_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_universe.systems')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attackers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_done', models.BigIntegerField()),
                ('final_blow', models.BooleanField()),
                ('security_status', models.FloatField()),
                ('alliance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.alliances')),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbeve_social.characters')),
                ('corporation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.corporations')),
                ('ship_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_items.shiptypes')),
                ('weapon_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_items.weapontypes')),
                ('killmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attackers', to='dbeve_social.killmails')),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_taken', models.BigIntegerField()),
                ('alliance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.alliances')),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbeve_social.characters')),
                ('corporation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.corporations')),
                ('killmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='dbeve_social.killmails')),
            ],
        ),
        migrations.CreateModel(
            name='VictimItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BigIntegerField()),
                ('status', models.CharField(choices=[('destroyed', 'Итем уничтожен'), ('dropped', 'Итем выпал')])),
                ('quantity', models.BigIntegerField()),
                ('item_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_items.items')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dbeve_social.victim')),
            ],
        ),
    ]
