# Generated by Django 5.0.2 on 2024-04-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0015_killmails_attackers_victim_victimitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='killmails',
            name='awox',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='killmails',
            name='destroyedValue',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='killmails',
            name='droppedValue',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='killmails',
            name='fittedValue',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='killmails',
            name='killmail_hash',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='killmails',
            name='locationID',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='killmails',
            name='npc',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='killmails',
            name='points',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='killmails',
            name='solo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='killmails',
            name='totalValue',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='attackers',
            name='damage_done',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attackers',
            name='final_blow',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='attackers',
            name='security_status',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='killmails',
            name='killmail_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='killmails',
            name='position_x',
            field=models.DecimalField(decimal_places=0, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='killmails',
            name='position_y',
            field=models.DecimalField(decimal_places=0, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='killmails',
            name='position_z',
            field=models.DecimalField(decimal_places=0, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='damage_taken',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='victimitems',
            name='flag',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='victimitems',
            name='quantity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='victimitems',
            name='status',
            field=models.CharField(choices=[('destroyed', 'Итем уничтожен'), ('dropped', 'Итем выпал')], null=True),
        ),
    ]
