# Generated by Django 5.0.2 on 2024-04-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_items', '0002_categories_groups_rename_items_types'),
        ('dbeve_social', '0016_killmails_awox_killmails_destroyedvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackers',
            name='ship_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackers_ship_type', to='dbeve_items.shiptypes'),
        ),
        migrations.AlterField(
            model_name='attackers',
            name='weapon_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackers_weapon_type', to='dbeve_items.weapontypes'),
        ),
    ]
