# Generated by Django 5.0.2 on 2024-04-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0018_alter_attackers_ship_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attackers',
            name='ship_type',
        ),
        migrations.RemoveField(
            model_name='attackers',
            name='weapon_type',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='ship_type',
        ),
        migrations.RemoveField(
            model_name='victimitems',
            name='item_type',
        ),
    ]
