# Generated by Django 5.0.2 on 2024-04-23 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_items', '0004_initial'),
        ('dbeve_social', '0019_remove_attackers_ship_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackers',
            name='ship_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackers_ship_type', to='dbeve_items.types'),
        ),
        migrations.AddField(
            model_name='attackers',
            name='weapon_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackers_weapon_type', to='dbeve_items.types'),
        ),
        migrations.AddField(
            model_name='killmails',
            name='ship_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_items.types'),
        ),
        migrations.AddField(
            model_name='victimitems',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_items.types'),
        ),
    ]
