# Generated by Django 5.0.2 on 2024-04-25 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0020_attackers_ship_type_attackers_weapon_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedKills',
            fields=[
                ('dt_change', models.DateTimeField(auto_now=True, null=True)),
                ('response_body', models.JSONField(null=True)),
                ('related_id', models.CharField(primary_key=True, serialize=False)),
                ('url', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='killmails',
            name='related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.relatedkills'),
        ),
    ]
