# Generated by Django 5.0.2 on 2024-04-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0021_relatedkills_killmails_related'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedKills',
            new_name='Relates',
        ),
    ]
