# Generated by Django 5.0.2 on 2024-04-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0022_rename_relatedkills_relates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relates',
            old_name='related_id',
            new_name='relate_id',
        ),
    ]
