# Generated by Django 5.0.2 on 2024-04-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0023_rename_related_id_relates_relate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relates',
            old_name='relate_id',
            new_name='related_id',
        ),
    ]
