# Generated by Django 5.0.2 on 2024-04-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0025_remove_killmails_related_killmails_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='killmails',
            name='related',
        ),
        migrations.AddField(
            model_name='relates',
            name='killmails',
            field=models.ManyToManyField(blank=True, to='dbeve_social.killmails'),
        ),
    ]
