# Generated by Django 5.0.2 on 2024-04-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0026_remove_killmails_related_relates_killmails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='killmails',
            old_name='points',
            new_name='pts',
        ),
        migrations.RenameField(
            model_name='killmails',
            old_name='totalValue',
            new_name='sumV',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='destroyedValue',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='droppedValue',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='fittedValue',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='locationID',
        ),
        migrations.AddField(
            model_name='killmails',
            name='day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='killmails',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
