# Generated by Django 5.0.2 on 2024-04-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0027_rename_points_killmails_pts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='killmails',
            old_name='sumV',
            new_name='sumv',
        ),
    ]
