# Generated by Django 5.0.2 on 2024-04-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0028_rename_sumv_killmails_sumv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relates',
            name='killmails',
            field=models.ManyToManyField(blank=True, related_name='relates', to='dbeve_social.killmails'),
        ),
    ]
