# Generated by Django 5.0.2 on 2024-04-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0029_alter_relates_killmails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='killmails',
            old_name='ship_type',
            new_name='victim_ship_type',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='awox',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='day',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='npc',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='pts',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='solo',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='time',
        ),
        migrations.AddField(
            model_name='killmails',
            name='victim_allinace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.alliances'),
        ),
        migrations.AddField(
            model_name='killmails',
            name='victim_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.characters'),
        ),
        migrations.AddField(
            model_name='killmails',
            name='victim_corporation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.corporations'),
        ),
    ]
