# Generated by Django 5.0.2 on 2024-05-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0031_rename_victim_allinace_killmails_victim_alliance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='killmails',
            options={'ordering': ['victim_alliance']},
        ),
    ]
