# Generated by Django 5.0.2 on 2024-05-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_items', '0007_alter_types_mass'),
        ('dbeve_social', '0036_battlereports_kmscount_battlereports_totalpilots_and_more'),
        ('dbeve_universe', '0016_bloodlines_dt_change_bloodlines_response_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='killmails',
            options={},
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='damage_taken',
            new_name='dmg',
        ),
        migrations.RemoveField(
            model_name='attackers',
            name='ship_type',
        ),
        migrations.RemoveField(
            model_name='attackers',
            name='weapon_type',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='victim_alliance',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='victim_character',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='victim_corporation',
        ),
        migrations.RemoveField(
            model_name='killmails',
            name='victim_ship_type',
        ),
        migrations.AddField(
            model_name='attackers',
            name='ship',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackers_ship_type', to='dbeve_items.types'),
        ),
        migrations.AddField(
            model_name='attackers',
            name='weapon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackers_weapon_type', to='dbeve_items.types'),
        ),
        migrations.AddField(
            model_name='victim',
            name='ship',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_items.types'),
        ),
        migrations.AlterField(
            model_name='killmails',
            name='solar_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='killmails', to='dbeve_universe.systems'),
        ),
    ]
