# Generated by Django 5.0.2 on 2024-05-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_items', '0007_alter_types_mass'),
        ('dbeve_social', '0037_alter_killmails_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Victim',
            new_name='Victims',
        ),
    ]
