# Generated by Django 5.0.2 on 2024-05-04 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_items', '0007_alter_types_mass'),
        ('dbeve_social', '0039_remove_victimitems_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attackers',
            fields=[
                ('attacker_id', models.CharField(primary_key=True, serialize=False)),
                ('damage_done', models.BigIntegerField(null=True)),
                ('final_blow', models.BooleanField(null=True)),
                ('security_status', models.FloatField(null=True)),
                ('alliance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.alliances')),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbeve_social.characters')),
                ('corporation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.corporations')),
                ('killmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attackers', to='dbeve_social.killmails')),
                ('ship', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackers_ship_type', to='dbeve_items.types')),
                ('weapon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackers_weapon_type', to='dbeve_items.types')),
            ],
        ),
        migrations.CreateModel(
            name='Victims',
            fields=[
                ('victim_id', models.CharField(primary_key=True, serialize=False)),
                ('dmg', models.BigIntegerField(null=True)),
                ('alliance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.alliances')),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbeve_social.characters')),
                ('corporation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.corporations')),
                ('killmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='dbeve_social.killmails')),
                ('ship', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_items.types')),
            ],
        ),
        migrations.CreateModel(
            name='VictimItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BigIntegerField(null=True)),
                ('status', models.CharField(choices=[('destroyed', 'Итем уничтожен'), ('dropped', 'Итем выпал')], null=True)),
                ('quantity', models.BigIntegerField(null=True)),
                ('item_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_items.types')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dbeve_social.victims')),
            ],
        ),
    ]
