# Generated by Django 5.0.2 on 2024-05-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0040_attackers_victims_victimitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackers',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='attackers',
            name='response_body',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='victimitems',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='victimitems',
            name='response_body',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='victims',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='victims',
            name='response_body',
            field=models.JSONField(null=True),
        ),
    ]
