# Generated by Django 5.0.2 on 2024-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0043_attackers_victims_victimitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackers',
            name='attacker_id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
