# Generated by Django 5.0.2 on 2024-05-04 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0044_alter_attackers_attacker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackers',
            name='killmail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attackers', to='dbeve_social.killmails'),
        ),
    ]
