# Generated by Django 5.0.2 on 2024-05-04 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0045_alter_attackers_killmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victims',
            name='killmail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='dbeve_social.killmails'),
        ),
    ]
