# Generated by Django 5.0.2 on 2024-05-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0047_alter_attackers_alliance_alter_attackers_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlereports',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
    ]
