# Generated by Django 5.0.2 on 2024-05-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_social', '0048_battlereports_time_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attackers',
        ),
    ]
