# Generated by Django 5.0.2 on 2025-05-13 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_items', '0007_alter_types_mass'),
        ('dbeve_social', '0049_delete_attackers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attackers',
            fields=[
                ('dt_change', models.DateTimeField(auto_now=True, null=True)),
                ('response_body', models.JSONField(null=True)),
                ('attacker_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('damage_done', models.BigIntegerField(null=True)),
                ('final_blow', models.BooleanField(null=True)),
                ('security_status', models.FloatField(null=True)),
                ('alliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.alliances')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbeve_social.characters')),
                ('corporation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbeve_social.corporations')),
                ('killmail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attackers', to='dbeve_social.killmails')),
                ('ship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackers_ship_type', to='dbeve_items.types')),
                ('weapon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackers_weapon_type', to='dbeve_items.types')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
