# Generated by Django 5.0.2 on 2024-03-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_to_esi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultJSON',
        ),
    ]
