# Generated by Django 5.0.2 on 2024-04-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_items', '0001_initial'),
        ('dbeve_social', '0016_killmails_awox_killmails_destroyedvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_change', models.DateTimeField(auto_now=True, null=True)),
                ('response_body', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_change', models.DateTimeField(auto_now=True, null=True)),
                ('response_body', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Types',
        ),
    ]
