# Generated by Django 5.0.2 on 2024-04-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_items', '0002_categories_groups_rename_items_types'),
        ('dbeve_social', '0019_remove_attackers_ship_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='ShipTypes',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
        migrations.DeleteModel(
            name='WeaponTypes',
        ),
    ]
