# Generated by Django 5.0.2 on 2024-04-24 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_items', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbeve_items.categories'),
        ),
        migrations.AddField(
            model_name='groups',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='published',
            field=models.BooleanField(null=True),
        ),
    ]
