# Generated by Django 5.0.2 on 2024-04-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_items', '0005_groups_category_groups_name_groups_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='capacity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='types',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='types',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbeve_items.groups'),
        ),
        migrations.AddField(
            model_name='types',
            name='mass',
            field=models.DecimalField(decimal_places=0, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='types',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='types',
            name='packaged_volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='types',
            name='portion_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='types',
            name='published',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='types',
            name='radius',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='types',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
    ]
