# Generated by Django 5.0.2 on 2024-04-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeve_items', '0006_types_capacity_types_description_types_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='mass',
            field=models.DecimalField(decimal_places=0, max_digits=40, null=True),
        ),
    ]
